name: dartcore
description: A simple, yet powerful Flask alternative for Dart. A lightweight framework offering fast performance, scalability, and efficient API development to build modern apps with ease and minimal code.
version: 0.0.3
repository: https://github.com/neoapps-dev/dartcore

environment:
  sdk: ^3.5.3
dependencies:
  http_parser: ^4.1.0
  mime: ^2.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0