name: dartcore
description: A simple, powerful Flask alternative for Dart, offering fast and efficient API development with scalability.
version: 0.0.4
repository: https://github.com/neoapps-dev/dartcore

environment:
  sdk: ^3.5.3
dependencies:
  http_parser: ^4.1.0
  mime: ^2.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0